### ISSUE TITLE
Non-latin words support

### ISSUE THREAD

**Issue by imposeren** [wriddhi/bskypt#1]
Currently receipt only shows lating words in top words. Can we maybe somehow use unicode aware regex or somehow else allow words with non-latin characters to be shown in results. By unicode aware I mean using `u`  flag:
https://mathiasbynens.be/notes/es6-unicode-regex

UPD: sorry, I'm not familiar with JS much, and looks like this flag does not affect `\w`  so some other solution should be used )=

**Comment by wriddhi** [comment]
Yup, great idea. Thanks for pointing out that obvious oversight. I'll fix it soon.

**Comment by wriddhi** [comment]
@imposeren just pushed a commit to fix this issue, would be awesome if you could verify if it now works as intended for non-latin languages

**Comment by imposeren** [comment]
Thanks! It works!
![image](https://github.com/user-attachments/assets/97c77063-f999-4b2b-b123-34bd02175cfd)

COmmon words are expectedly not defined in your code, so there things to improve... What about treating all 1 letter words as "common words"? There definitely will be some exceptions, but in most cases excluding 1-letter words will solve most of the cyrillic conjunctions. 2-letter words are also good candidate, but I guess it's too risky to also exclude them

**Comment by wriddhi** [comment]
You make a good point, I can filter 1 letter words, my only concern being some languages like Japanese may have some 1 letter kanji characters that express a whole meaningful phrase by itself. 2 letters being more risky when they can even make a complete sentence.

I will go ahead and exclude 1 letter characters for now as I do think it provides more meaningful insights for the majority of users anyways

**Comment by imposeren** [comment]
yeap 1 symbol word exclusion may totally not work for some languages, so it might be required to differentiate different symbols...

In any case: thanks for quick fix, initial issue is resolved and common words is a completely different thing

**Comment by imposeren** [comment]
@wriddhi minor followup: in the upcoming stopwords==3.1.2 there will be a lot more Ukrainian stopwords, so ukrainian "Favorite words" should become better after that

https://github.com/fergiemcdowall/stopword/releases/tag/v3.1.2

**Comment by wriddhi** [comment]
@imposeren absolutely, I'll keep an eye on their next release
