### ISSUE TITLE
[Discussion] How does this work?

### ISSUE THREAD

**Issue by JRDK92** [wriddhi/bskypt#2]
How exactly does this work? There's a readme, but I'm very curious to know how the program runs and functions at a high level. Is there some kind of API that ingests data from Bsky app, and then sends it somewhere else? Curious to know more! Looks great.

**Comment by wriddhi** [comment]
Sure, this is a very simple app that takes in user handle through input and then fetches 2 pieces of data using that user handle:

1. The [User Profile](https://docs.bsky.app/docs/api/app-bsky-actor-get-profile) data
2. The [User Feed](https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed) data.

These pieces of data are then parsed and shown as a receipt through some minimal calculations. It's as simple as it gets!
