### ISSUE TITLE
Count accuracy questions

### ISSUE THREAD

**Issue by cyrneko** [wriddhi/bskypt#3]
Hi there! I've discovered this after a friend sent me one of their receipts and upon inputting my handle (@cyrneko.eu) I noticed that I supposedly got 2.376.460 likes!?

To compare, bskypt says @bsky.app got 3.952.147 likes

There's no way I got almost half as many likes as bsky.app, right? I dont have any posts with 230K likes on their own like Bluesky themselves do, the best I have is a couple hundred 🤔

**Comment by wriddhi** [comment]
Yup, that was an issue where your like counts were involving likes of posts that your had reposted too. It should now only consider posts where you are the author. Check it out and lemme know if this is accurate after the update
![cyrneko eu-bskypt](https://github.com/user-attachments/assets/31965416-ae3e-4ee6-ac18-15d7643b85b1)
